name: Sync Leetcode

on:
  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Runs automatically every day at 11:55 PM IST (which is 6:25 PM UTC)
    - cron: "25 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: nbhv-leetcode-solutions
          filter-duplicate-secs: 0
